name: Mirror to Professional GitHub

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror repository
        env:
          PROFESSIONAL_GITHUB_TOKEN: ${{ secrets.PROFESSIONAL_GITHUB_TOKEN }}
        run: |
          git clone --mirror https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/NatoJenkins/MLB-WinForecaster.git repo
          cd repo
          git push https://x-access-token:${PROFESSIONAL_GITHUB_TOKEN}@github.com/silverreyes/MLB-WinForecaster.git --mirror
